---
kind: Service
apiVersion: v1
metadata:
  name: rds-{{.Replica}}
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: http1
      protocol: TCP
      port: 81
      targetPort: 8081
  type: ClusterIP
